import car1 from "./public/cars/1.png";
import car2 from "./public/cars/2.png";
import car3 from "./public/cars/3.png";
import car4 from "./public/cars/4.png";
import car5 from "./public/cars/5.png";
import car6 from "./public/cars/6.png";
import car7 from "./public/cars/7.png";
import car8 from "./public/cars/8.png";
import car9 from "./public/cars/9.png";
import car10 from "./public/cars/10.png";
import car11 from "./public/cars/11.png";
import car12 from "./public/cars/12.png";
import view1 from "./public/cars/view1.png";
import view2 from "./public/cars/view2.png";

const carsData = [
  {
    id: 1,
    name: "Koenigsegg",
    type: "Sport",
    image: car1,
    views: [view1, view2],
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    capacity: 2,
    steering: "Auto",
    fuel: 90,
    price: 99,
    newPrice: 0,
  },
  {
    id: 2,
    name: "Nissan GT-R",
    type: "Sport",
    image: car2,
    views: [view1, view2],
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    capacity: 2,
    steering: "Auto",
    fuel: 80,
    price: 100,
    newPrice: 80,
  },
  {
    id: 3,
    name: "Rolls-Royce",
    type: "Sedan",
    image: car3,
    views: [view1, view2],
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    capacity: 4,
    steering: "Manual",
    fuel: 70,
    price: 96,
    newPrice: 0,
  },
  {
    id: 4,
    name: "Nissan GT-R",
    type: "Sport",
    image: car4,
    views: [view1, view2],
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    capacity: 2,
    steering: "Auto",
    fuel: 80,
    price: 100,
    newPrice: 80,
  },
  {
    id: 5,
    name: "All New Rush",
    type: "SUV",
    image: car5,
    views: [view1, view2],
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    capacity: 6,
    steering: "Manual",
    fuel: 70,
    price: 80,
    newPrice: 72,
  },
  {
    id: 6,
    name: "CR - V",
    type: "SUV",
    image: car6,
    views: [view1, view2],
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    capacity: 6,
    steering: "Manual",
    fuel: 80,
    price: 80,
    newPrice: 0,
  },
  {
    id: 7,
    name: "All New Terios",
    type: "SUV",
    image: car7,
    views: [view1, view2],
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    capacity: 2,
    steering: "Manual",
    fuel: 90,
    price: 74,
    newPrice: 0,
  },
  {
    id: 8,
    name: "CR - V",
    type: "SUV",
    image: car8,
    views: [view1, view2],
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    capacity: 6,
    steering: "Manual",
    fuel: 80,
    price: 80,
    newPrice: 0,
  },
  {
    id: 9,
    name: "MG ZX Exclusice",
    type: "Hatchback",
    image: car9,
    views: [view1, view2],
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    capacity: 4,
    steering: "Manual",
    fuel: 70,
    price: 80,
    newPrice: 76,
  },
  {
    id: 10,
    name: "New MG ZS",
    type: "SUV",
    image: car10,
    views: [view1, view2],
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    capacity: 6,
    steering: "Manual",
    fuel: 70,
    price: 80,
    newPrice: 0,
  },
  {
    id: 11,
    name: "MG ZX Excite",
    type: "Hatchback",
    image: car11,
    views: [view1, view2],
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    capacity: 4,
    steering: "Manual",
    fuel: 90,
    price: 74,
    newPrice: 0,
  },
  {
    id: 12,
    name: "New MG ZS",
    type: "SUV",
    image: car12,
    views: [view1, view2],
    description: `NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the "race track".`,
    capacity: 6,
    steering: "Manual",
    fuel: 80,
    price: 80,
    newPrice: 0,
  },
];

export default carsData;
