import Head from "next/head";
import MainLayout from "@/components/layout/mainLayout";
import PopularCars from "@/components/popularCars";

export default function Home() {
  return (
    <>
      <Head>
        <title>MORENT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <PopularCars />
      </MainLayout>
    </>
  );
}
