import Head from "next/head";
import MainLayout from "@/components/layout/mainLayout";
import PopularCars from "@/components/popularCars";
import React from "react";
import PickDrop from "@/components/pickDropComponent";
export interface Car {
  id: number;
  name: string;
  type: string;
  image: string;
  views: string[];
  description: string;
  capacity: number;
  steering: string;
  fuel: number;
  price: number;
  newPrice: number;
}

export interface Cars {
  cars: Car[];
}

export default function Home({ cars }: Cars) {
  return (
    <>
      <Head>
        <title>MORENT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <PickDrop />
        <PopularCars cars={cars} />
      </MainLayout>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/db/cars");
  const cars = await res.json();

  return {
    props: {
      cars,
    },
  };
}
