import Head from "next/head";
import MainLayout from "@/components/layout/mainLayout";
import carsData from "../cars.js";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>MORENT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div className="h-96 bg-light-secondary"></div>
      </MainLayout>
    </>
  );
}
